import { Vehicle, MechanicShop, ServiceBooking, CraneTowDispatch, MaintenanceTask } from "./types";

export const initialVehicles: Vehicle[] = [
  {
    id: "veh-1",
    make: "Volkswagen",
    model: "Polo GT TSI",
    year: 2021,
    regNumber: "KL 07 CD 4488",
    fuelType: "Petrol",
    currentKm: 42350,
    lastServiceKm: 35000,
    nextServiceDueKm: 45000,
    healthScore: 84,
    insuranceExpiry: "2026-11-15",
    pollutionExpiry: "2026-10-20",
  },
  {
    id: "veh-2",
    make: "Hyundai",
    model: "Creta SX(O)",
    year: 2022,
    regNumber: "KL 01 BY 9012",
    fuelType: "Diesel",
    currentKm: 28120,
    lastServiceKm: 20000,
    nextServiceDueKm: 30000,
    healthScore: 92,
    insuranceExpiry: "2027-04-10",
    pollutionExpiry: "2027-01-05",
  },
];

export const sampleMaintenanceTasks: MaintenanceTask[] = [
  {
    id: "task-1",
    vehicleId: "veh-1",
    title: "Engine Oil & Filter Replacement",
    intervalKm: 10000,
    lastDoneKm: 35000,
    dueKm: 45000,
    status: "due_soon",
    estimatedCost: 3800,
    description: "Fully synthetic 5W-40 oil with OEM German cartridge filter.",
  },
  {
    id: "task-2",
    vehicleId: "veh-1",
    title: "Front Brake Pads Inspection",
    intervalKm: 20000,
    lastDoneKm: 25000,
    dueKm: 45000,
    status: "due_soon",
    estimatedCost: 2600,
    description: "Brembo ceramic compound recommended for high heat resistance.",
  },
  {
    id: "task-3",
    vehicleId: "veh-1",
    title: "Brake Fluid Flush (DOT 4)",
    intervalKm: 30000,
    lastDoneKm: 15000,
    dueKm: 45000,
    status: "good",
    estimatedCost: 1200,
    description: "Hydraulic moisture content test and complete pressure bleeding.",
  },
  {
    id: "task-4",
    vehicleId: "veh-1",
    title: "Cabin Air & AC Antibacterial Cleansing",
    intervalKm: 15000,
    lastDoneKm: 35000,
    dueKm: 50000,
    status: "good",
    estimatedCost: 850,
    description: "Activated carbon filter replacement and evaporator foam cleaning.",
  },
];

export const sampleMechanicShops: MechanicShop[] = [
  {
    id: "shop-1",
    name: "Apex Auto Precision & Diagnostics",
    rating: 4.9,
    reviewsCount: 184,
    distanceKm: 2.4,
    address: "Kaloor - Kadavanthra Rd, Kochi, Kerala",
    phone: "+91 98470 11223",
    isOpenNow: true,
    isEmergencyCapable: true,
    activeBays: 3,
    totalBays: 5,
    supportedMakes: ["Volkswagen", "Skoda", "Audi", "BMW", "Hyundai", "Toyota"],
    services: [
      { id: "s-1", name: "Comprehensive Periodic Service", category: "Periodic", price: 4200, durationMinutes: 180 },
      { id: "s-2", name: "Brake Overhaul & Fluid Bleeding", category: "Brakes", price: 1800, durationMinutes: 90 },
      { id: "s-3", name: "Computerised OBD-II Diagnostic Scan", category: "Electrical", price: 950, durationMinutes: 45 },
      { id: "s-4", name: "Suspension Bushing & Strut Refresh", category: "Suspension", price: 3400, durationMinutes: 240 },
    ],
  },
  {
    id: "shop-2",
    name: "SpeedCraft Motor Works",
    rating: 4.7,
    reviewsCount: 96,
    distanceKm: 4.1,
    address: "NH 66 Bypass, Edappally, Kochi, Kerala",
    phone: "+91 97455 33441",
    isOpenNow: true,
    isEmergencyCapable: true,
    activeBays: 2,
    totalBays: 4,
    supportedMakes: ["Maruti Suzuki", "Hyundai", "Tata", "Mahindra", "Honda"],
    services: [
      { id: "s-5", name: "Express Oil Service", category: "Periodic", price: 2800, durationMinutes: 75 },
      { id: "s-6", name: "Clutch Plate & Flywheel Overhaul", category: "Engine", price: 5500, durationMinutes: 300 },
      { id: "s-7", name: "Cooling System Flush & Radiator Leak Test", category: "Engine", price: 1500, durationMinutes: 60 },
    ],
  },
  {
    id: "shop-3",
    name: "Torque Garage European Specialists",
    rating: 4.8,
    reviewsCount: 142,
    distanceKm: 5.8,
    address: "Seaport - Airport Rd, Kakkanad, Kochi, Kerala",
    phone: "+91 94471 88990",
    isOpenNow: false,
    isEmergencyCapable: false,
    activeBays: 4,
    totalBays: 4,
    supportedMakes: ["Volkswagen", "Skoda", "Audi", "Mercedes-Benz", "BMW"],
    services: [
      { id: "s-8", name: "DSG Transmission Service", category: "Engine", price: 8500, durationMinutes: 240 },
      { id: "s-9", name: "Timing Belt & Water Pump Kit", category: "Engine", price: 7200, durationMinutes: 360 },
    ],
  },
];

export const sampleBookings: ServiceBooking[] = [
  {
    id: "bk-101",
    bookingNumber: "GU-2026-8812",
    customerId: "cust-1",
    customerName: "Vehicle Owner #108",
    customerPhone: "+91 98950 12345",
    vehicle: {
      make: "Volkswagen",
      model: "Polo GT TSI",
      regNumber: "KL 07 CD 4488",
      currentKm: 42350,
    },
    shopId: "shop-1",
    shopName: "Apex Auto Precision & Diagnostics",
    services: [
      { id: "s-1", name: "Comprehensive Periodic Service", category: "Periodic", price: 4200, durationMinutes: 180 },
      { id: "s-2", name: "Brake Overhaul & Fluid Bleeding", category: "Brakes", price: 1800, durationMinutes: 90 },
    ],
    status: "in_progress",
    scheduledTime: "Today, 10:30 AM",
    loggedOdometer: 42352,
    partsReplaced: [
      { name: "Synthetic 5W-40 Engine Oil (4.2L)", cost: 3200 },
      { name: "OEM Oil Filter Cartridge", cost: 580 },
      { name: "Front Ceramic Brake Pads Pair", cost: 2400 },
    ],
    laborCharge: 1800,
    notes: "Customer reported squeal on high-speed braking.",
    createdAt: "2026-09-30 08:15",
    completionOtp: "4921",
  },
  {
    id: "bk-102",
    bookingNumber: "GU-2026-8845",
    customerId: "cust-2",
    customerName: "Vehicle Owner #214",
    customerPhone: "+91 94460 67890",
    vehicle: {
      make: "Hyundai",
      model: "Creta SX(O)",
      regNumber: "KL 01 BY 9012",
      currentKm: 28120,
    },
    shopId: "shop-1",
    shopName: "Apex Auto Precision & Diagnostics",
    services: [
      { id: "s-3", name: "Computerised OBD-II Diagnostic Scan", category: "Electrical", price: 950, durationMinutes: 45 },
    ],
    status: "pending",
    scheduledTime: "Today, 03:00 PM",
    laborCharge: 950,
    notes: "ABS warning lamp flashing periodically on highway speeds.",
    createdAt: "2026-09-30 11:20",
    completionOtp: "7730",
  },
];

export const sampleCraneDispatches: CraneTowDispatch[] = [
  {
    id: "tow-501",
    dispatchNumber: "TOW-2026-049",
    customerId: "cust-3",
    customerPhone: "+91 97441 55667",
    vehicleInfo: {
      make: "Skoda",
      model: "Octavia vRS",
      regNumber: "KL 07 BR 3322",
      condition: "severe_damage",
    },
    pickupAddress: "Near Container Terminal Rd, Kalamassery, Kochi",
    destinationShopId: "shop-1",
    destinationShopName: "Apex Auto Precision & Diagnostics",
    destinationAddress: "Kaloor - Kadavanthra Rd, Kochi",
    distanceKm: 8.4,
    baseFare: 1500,
    perKmRate: 65,
    totalFare: 2046,
    status: "en_route",
    photos: {
      front: true,
      rear: true,
      left: true,
      right: false,
    },
    handoverOtp: "8319",
    driverName: "Fleet Unit #4 (Hydraulic Bed)",
    driverPhone: "+91 98460 77112",
    truckPlate: "KL 07 CW 9901",
    createdAt: "2026-09-30 11:45",
  },
  {
    id: "tow-502",
    dispatchNumber: "TOW-2026-050",
    customerId: "cust-4",
    customerPhone: "+91 99951 88334",
    vehicleInfo: {
      make: "Tata",
      model: "Harrier XZA+",
      regNumber: "KL 40 G 6611",
      condition: "rolls_freely",
    },
    pickupAddress: "Highway Toll Plaza, Kumbalam, Kochi",
    destinationShopId: "shop-2",
    destinationShopName: "SpeedCraft Motor Works",
    destinationAddress: "NH 66 Bypass, Edappally, Kochi",
    distanceKm: 14.2,
    baseFare: 1500,
    perKmRate: 65,
    totalFare: 2423,
    status: "dispatched",
    photos: {},
    handoverOtp: "1594",
    driverName: "Fleet Unit #2 (Wheel Lift)",
    driverPhone: "+91 98460 44221",
    truckPlate: "KL 07 BW 4410",
    createdAt: "2026-09-30 12:10",
  },
];
